name: Block PRs with Issue Links

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-for-issue-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check for issue references in PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || "";
            const title = pr.title || "";

            const issuePattern = /(?:close[sd]?|fix(e[sd])?|resolve[sd]?|#)\s*#?\d+/gi;

            if (issuePattern.test(body) || issuePattern.test(title)) {
              core.setFailed("This PR references an issue. Please confirm manually before merging.");
            } else {
              core.info("No issue reference found — good to merge.");
            }
